services:
  web_agronomia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-agronomia
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge